### ISSUE TITLE
Add a link in the repo title to https://distcc.github.io/

### ISSUE THREAD

**Issue by thinrope** [distcc/distcc.github.io#2]
The distcc website: https://distcc.github.io/ (code is at https://github.com/distcc/distcc/ )

**Comment by sourcefrog** [comment]
Fixed - with the new canonical name, https://distcc.org/
<img width="277" alt="Screenshot showing distcc.org" src="https://user-images.githubusercontent.com/346355/152656856-f9a94728-9c11-4896-b2e3-54a950c2a903.png">
