### ISSUE TITLE
60 seconds description is wrong

### ISSUE THREAD

**Issue by marehr** [distcc/distcc.github.io#4]
https://github.com/distcc/distcc.github.io/blob/3231b145ee2915033f6d532dfc80276f1d952a3b/index.html#L76-L90

Should be `./autogen.sh && ./configure && make && sudo make install`

**Comment by sourcefrog** [comment]
Doesn't the tarball contain the generated configure script any more?

**Comment by marehr** [comment]
Oh you're right, I used the git checkout instead of the tarball and tried the 60 seconds thing and it did not work. tarball has that contained. Sorry for the noise.

**Comment by sourcefrog** [comment]
No problem. We could add that, but I feel like people who want to build from head would know this(?) and I'd like to keep the short version short.

**Comment by marehr** [comment]
I personally like to build from source with git history, but nowadays you encounter autoconf(?) not as frequently in projects anymore, so without searching for the right steps this was a hurdle for me. Fortunately, you had a travis script that showed me the instructions I needed to know :)
